### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by StickHu** [EvaYiwenWang/PLSDAbatch#1]
Great work for the batch removal. However, if I want to use the PLSDAbatch to deal with the WGS metagenome data, such as the genus-level or the species-level relative abundance among different datasets, do you have the command lines recommanded? Thanks for your help.

**Comment by EvaYiwenWang** [comment]
Hello StickHu,

Many thanks for being interested into our methods. You can install our package first with devtools::install_github("https://github.com/EvaYiwenWang/PLSDAbatch", build_vignettes = T), then you are able to see the guide file with command: browseVignettes("PLSDAbatch"). I am here to help if you have any more issues. 

Best regards,
Eva

**Comment by StickHu** [comment]
Hi Eva,

    I have some problems in using the Plsda-batch. First, I have used the four kinds of data you provided in the website. However, I don't know how to deal with the data which doesn't belong to them. My metagenomic data includes different tissue types of people that have different diseases. And I want to investigate the effect of diseases on different tissue types and the microbial abundance of different tissue types. But it has a problem of collinearity. Could you please help me solve that? 
    Besides, I still find that the batch correction of sPLSDA-batch and PLSDA-batch didn't completely remove batch effects but retains more intrested interaction factors than other methods. So I'm not sure that the method is better than others, do you have some advices? Thanks.

Best wishes,
StickHu
