### ISSUE TITLE
Addition of `vegan::pca()` breaks PLSDAbatch

### ISSUE THREAD

**Issue by gavinsimpson** [EvaYiwenWang/PLSDAbatch#4]
Because you import the entire vegan namespace at the *end* of your `NAMESPACE`, our adding `vegan::pca()` breaks your package.

For example, https://github.com/EvaYiwenWang/PLSDAbatch/blob/779db4d05ab8cbdd894b9e0753f81aeeff4330c6/R/alignment_score.R#L54

will now be run with `vegan::pca()` not the intended `mixOmics::pca()`. Ideally, you would change to selectively importing from the vegan namespace only those functions that you actually use. If you don't want to do that, you'll need to use the fully-qualified function name, in this case `mixOmics::pca( ... )`, but that will still raise a warning from `R CMD check`.

We are planning to release a version of vegan with these changes in August (although that may slip).

**Comment by EvaYiwenWang** [comment]
Hello Gavin,
I see the issue, will update my package soon to fix that. Many thanks!

Best regards,
Eva
