### ISSUE TITLE
Negative values in X.nobatch

### ISSUE THREAD

**Issue by EOzcariz** [EvaYiwenWang/PLSDAbatch#6]
Dear Eva,

I used your the PLSDA_batch function to correct a batch in the filtered count matrix of my microbiome experiment. As the following step would be to perform a compositional differential abundance (CoDA) analysis I used the filtered counts as inputs (instead of the log transformed data) after having added a pseudocount of 1.

However, I am getting negative values in the batch corrected matrix. Why is this happening?

Since I cannot share my date, I reproduce belowthe code with the example in the vignette.

Thanks a lot,
Enrique

data('AD_data') 
ad.count <- assays(AD_data$FullData)$Count
ad.metadata <- rowData(AD_data$FullData)
ad.batch = factor(ad.metadata$sequencing_run_date, 
                  levels = unique(ad.metadata$sequencing_run_date))
ad.trt = as.factor(ad.metadata$initial_phenol_concentration.regroup)

ad.sPLSDA_batch.res <- PLSDA_batch(X = ad.clr, 
                                   Y.trt = ad.trt, Y.bat = ad.batch,
                                   ncomp.trt = 1, keepX.trt = 100,
                                   ncomp.bat = 4)

**Comment by EvaYiwenWang** [comment]
Hi,

Sorry for the slow reply! Here are some possible reasons for the negative values: 
1. The input data for PLSDA-batch are centered log ratio (CLR) transformed. 
2. PLSDA-batch centers and scales each taxon (column) in the input data.
If you are using CoDA, you can add the batch as covariates to account for it. If you are using PLSDA-batch to remove batch effects, try using linear regression or even better a multivariate method like PLSDA. No need to worry about the compostional constraint, as CLR handles that for you.

Best,
Eva
